# More info around this file at https://www.git-town.com/configuration-file

[branches]
main = "main"
perennials = []
perennial-regex = ""

[create]
share-new-branches = "no"
new-branch-type = "feature"

[hosting]
dev-remote = "origin"
platform = "github"

[ship]
delete-tracking-branch = false
strategy = "api"

[sync]
tags = true
feature-strategy = "rebase"
perennial-strategy = "rebase"
prototype-strategy = "rebase"
push-hook = true
upstream = true
