[project]
name = "ray-multi-worker"

[project.state_backend.local]
path = "./state.json"

[project.user_state_backend.local]
path = "./user_state.json"

[project.services.head]
image = "docker.io/rayproject/ray:latest"
command = "ray start --head --port 6379 --dashboard-host 0.0.0.0 --dashboard-port 8265 --block"
cpus = 1000
memory = 4096
internal_port = 8265
external_port = 80

[project.services.worker_1]
image = "docker.io/rayproject/ray:latest"
command = "ray start --address head:6379 --block"
cpus = 1000
memory = 4096
depends_on = ["head"]
