name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
type: Bug
projects: ["opencloudtool/1"]
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide detailed description of the bug
    validations:
      required: true
  - type: textarea
    id: stack-trace
    attributes:
      label: Stack Trace
      description: Please provide stack trace of the error
    validations:
      required: false
