[project]
name = "rest-service-with-domain"
domain = "test.opencloudtool.com"

[project.state_backend.local]
path = "./state.json"

[project.user_state_backend.local]
path = "./user_state.json"

[project.services.app_1]
image = "ghcr.io/opencloudtool/example-python-fastapi:latest"
cpus = 250
memory = 64

[project.services.app_1.envs]
APP_NAME = "app_1"

[project.services.app_2]
image = "ghcr.io/opencloudtool/example-python-fastapi:latest"
cpus = 250
memory = 64

[project.services.app_2.envs]
APP_NAME = "app_2"

[project.services.nginx]
image = "ghcr.io/opencloudtool/nginx-with-conf:latest"
internal_port = 80
external_port = 80
cpus = 250
memory = 64
depends_on = ["app_1", "app_2"]

[project.services.nginx.envs]
NGINX_CONF = """
events {
    worker_connections 1024;
}

http {
    server {
        server_name app_1.instance_1.test.opencloudtool.com;
        location / {
            proxy_pass http://app_1:8000;
        }
    }
    server {
        server_name app_2.instance_1.test.opencloudtool.com;
        location / {
            proxy_pass http://app_2:8000;
        }
    }
}
"""
