[project]
name = "s3-remote-state-storage"

[project.state_backend.s3]
region = "us-west-2"
bucket = "oct-state"
key = "state.json"

[project.user_state_backend.s3]
region = "us-west-2"
bucket = "oct-user-state"
key = "user_state.json"

[project.services.app_1]
image = "ghcr.io/opencloudtool/example-python-fastapi:latest"
cpus = 250
memory = 64
internal_port = 8000
external_port = 80

[project.services.app_1.envs]
APP_NAME = "app_1"
